apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: tonytran1997/todo-app:staging-latest  # Sử dụng image mới nhất
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: staging
spec:
  type: NodePort  # Thay đổi LoadBalancer thành NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Port mở trên các node (có thể thay đổi)
  selector:
    app: todo-app
