apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: staging
spec:
  replicas: 2  # Số lượng bản sao của ứng dụng
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: tonytran1997/todo-app:staging-latest  # Đây là tag mà Jenkins sẽ cập nhật sau khi push image lên Docker Hub
        ports:
        - containerPort: 80  # Port mà Nginx sẽ chạy bên trong container
        imagePullPolicy: Always  # Đảm bảo luôn kéo image mới nhất
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: staging
spec:
  type: ClusterIP  # Chỉ cần ClusterIP, không cần LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: todo-app
