apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: tonytran1997/todo-app:staging-latest  
        ports:
        - containerPort: 80 
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: todo-app
